# Allows for the definition of PR and Issue /commands
name: 'ðŸ“Ÿ Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  dispatch:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
